on: [workflow_dispatch]

jobs:
  codemakerai_generation_job:
    runs-on: ubuntu-latest
    name: A job to run codemakerai code generation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Code generation
        uses: codemakerai/codemaker-action@v1.5.0
        with:
          api-key: ${{ secrets.CODEMAKER_API_KEY }}
          mode: code
          path: ./example.java
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Code generated by codemaker
          title: Changes by codemaker-action
          body: This pull request contains code generated by codemaker.
          branch: codemakerai-generate
